const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(path.resolve(__dirname,'schedule-polling.js'),'utf8'),results=[];
function events(){const handlers={};return {handlers,addEventListener:(n,f)=>(handlers[n]??=new Set()).add(f),removeEventListener:(n,f)=>handlers[n]?.delete(f),emit:n=>handlers[n]?.forEach(f=>f())};}
function env(){let now=0,next=1;const timers=new Map(),intervals=new Map(),requests=[],received=[],win=events(),doc=events();doc.visibilityState='visible';win.setTimeout=(f,ms)=>{const id=next++;timers.set(id,{f,ms});return id;};win.clearTimeout=id=>timers.delete(id);win.setInterval=(f,ms)=>{const id=next++;intervals.set(id,{f,ms});return id;};win.clearInterval=id=>intervals.delete(id);const context=vm.createContext({window:win,document:doc,AbortController,Date:{now:()=>now},encodeURIComponent,fetch:(url,options)=>new Promise((resolve,reject)=>{requests.push({url,options,resolve,reject});options.signal.addEventListener('abort',()=>reject(Error('aborted')));})});vm.runInContext(source,context);return {context,win,doc,timers,intervals,requests,received,time:x=>now=x,start:month=>context.SharaSchedulePollV1('https://example.invalid/exec',month||'Септември 2026',x=>received.push(x))};}
const settle=async()=>{for(let i=0;i<5;i++)await Promise.resolve();};
async function ok(e,index=0,terms=[{day:'Вторник',time:'17:00–18:00',enrolled:20}]){e.requests[index].resolve({ok:true,json:async()=>({success:true,terms})});await settle();}
async function test(name,fn){try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});console.error(name,e.stack);}}
(async()=>{
await test('first visible load fetches immediately with no-store',async()=>{const e=env();e.start();assert.strictEqual(e.requests.length,1);assert.strictEqual(e.requests[0].options.cache,'no-store');assert(e.requests[0].url.includes(encodeURIComponent('Септември 2026')));await ok(e);assert.strictEqual(e.received.length,1);});
await test('interval is 60 seconds, not 10',async()=>{const e=env();e.start();assert.strictEqual([...e.intervals.values()][0].ms,60000);});
await test('slow request never overlaps with focus or interval',async()=>{const e=env();e.start();e.time(60000);e.win.emit('focus');[...e.intervals.values()][0].f();assert.strictEqual(e.requests.length,1);await ok(e);});
await test('focus and visibility bursts are throttled',async()=>{const e=env();e.start();await ok(e);e.time(1000);e.win.emit('focus');e.doc.emit('visibilitychange');assert.strictEqual(e.requests.length,1);e.time(16000);e.win.emit('focus');e.doc.emit('visibilitychange');assert.strictEqual(e.requests.length,2);});
await test('hidden tabs do not request and resume when visible',async()=>{const e=env();e.doc.visibilityState='hidden';e.start();assert.strictEqual(e.requests.length,0);e.time(60000);[...e.intervals.values()][0].f();assert.strictEqual(e.requests.length,0);e.doc.visibilityState='visible';e.doc.emit('visibilitychange');assert.strictEqual(e.requests.length,1);});
await test('cleanup aborts request and removes event listeners',async()=>{const e=env(),stop=e.start();stop();assert(e.requests[0].options.signal.aborted);await settle();assert.strictEqual(e.intervals.size,0);assert.strictEqual(e.timers.size,0);e.time(60000);e.win.emit('focus');assert.strictEqual(e.requests.length,1);});
await test('late response after cleanup cannot update UI',async()=>{const e=env(),stop=e.start();e.requests[0].resolve({ok:true,json:async()=>({success:true,terms:[]})});stop();await settle();assert.strictEqual(e.received.length,0);});
await test('failure preserves display and a later attempt succeeds',async()=>{const e=env();e.start();e.requests[0].reject(Error('network'));await settle();assert.strictEqual(e.received.length,0);e.time(60000);[...e.intervals.values()][0].f();await ok(e,1);assert.strictEqual(e.received.length,1);});
await test('timeout aborts and releases the in-flight guard',async()=>{const e=env();e.start();const timer=[...e.timers.values()][0];assert.strictEqual(timer.ms,30000);timer.f();await settle();e.time(60000);e.win.emit('focus');assert.strictEqual(e.requests.length,2);});
await test('malformed successful response cannot replace current terms',async()=>{const e=env();e.start();e.requests[0].resolve({ok:true,json:async()=>({success:true,terms:null})});await settle();assert.strictEqual(e.received.length,0);});
await test('non-OK HTTP response cannot replace current terms',async()=>{const e=env();e.start();e.requests[0].resolve({ok:false});await settle();assert.strictEqual(e.received.length,0);});
await test('complete bundle parses and preserves parent attendance and endpoint',async()=>{const code=fs.readFileSync(path.resolve(__dirname,'../assets/index-speed-v1.js'),'utf8'),old=fs.readFileSync(path.resolve(__dirname,'../assets/index-attendance-v1.js'),'utf8');new vm.Script(code);assert(code.includes('function SharaAttendanceV1'));assert(code.includes('action=membership'));assert.strictEqual(code.match(/https:\/\/script\.google\.com\/macros\/s\/[^`]+/)[0],old.match(/https:\/\/script\.google\.com\/macros\/s\/[^`]+/)[0]);assert(!code.includes('window.setInterval(t,1e4)'));});
const out={mode:'LOCAL_MOCK_NO_NETWORK',passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,total:results.length,results};fs.writeFileSync(path.join(__dirname,'polling-results.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({...out,results:undefined}));if(out.failed)process.exitCode=1;
})();
